apiVersion: v1
kind: Service
metadata:
  name: ntp-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: ntp-exporter
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: 9559
      protocol: TCP
      name: metrics
  selector:
    app: ntp-exporter
    role: metrics-exporter
