image:
  repository: sapcc/ntp-exporter
  tag: v2.1.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 128Mi
    ephemeral-storage: 16Mi
  limits:
    cpu: 100m
    memory: 256Mi
    ephemeral-storage: 16Mi

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 9559

ntp:
  source: cli
  server: de.pool.ntp.org
  measurementDuration: 30s
  protocolVersion: 4